### ISSUE TITLE
Add to CocoaPods repo

### ISSUE THREAD

**Issue by DagAgren** [zalando/SwiftMonkey#14]
SwiftMonkey and SwiftMonkeyPaws should be properly added to CocoaPods. I have no idea how yet, so if anyone wants to do it quickly, please go ahead!

**Comment by jonasman** [comment]
I recommend you doing it. Otherwise it will be in the other person's account

`pod trunk push`

https://guides.cocoapods.org/making/getting-setup-with-trunk.html
