### ISSUE TITLE
Not supporting iOS8, as the README states?

### ISSUE THREAD

**Issue by sfla** [zalando/SwiftMonkey#16]
I am trying to install SwiftMonkey using CocoaPods. My podfile specifies platform :ios, '8.0', but when I try to update it says the following:

[!] Unable to satisfy the following requirements:

- `SwiftMonkey (= 1.0)` required by `Podfile`

Specs satisfying the `SwiftMonkey (= 1.0)` dependency were found, but they required a higher minimum deployment target.

The README specifically states: "It has no dependencies other than iOS itself (8.0 and up should work). SwiftMonkeyPaws doesn't have any dependencies, either; you can even use on its own, without SwiftMonkey."

Am I doing something wrong?

**Comment by DagAgren** [comment]
No, it seems I have set the iOS version to 9.0 in the podspec files. I am now unsure if I actually used any iOS 9 features, or if the code would actually work on iOS 8.

If you want, you can try to manually put the files from this repo in your project and build and test it on iOS 8, and if it does work I can change the podspecs. (Or if not, the README.)

**Comment by DagAgren** [comment]
Merged insidegui's fix, which should fix the problem. I still need to make a new release but I'll try to get around to that on Monday.
