### ISSUE TITLE
Can not run on real device

### ISSUE THREAD

**Issue by lina1** [zalando/SwiftMonkey#20]
when I try to run test on real device, I got the following error:

`Library not loaded: @rpath/SwiftMonkey.framework/SwiftMonkey`

I can run it on simulator

**Comment by DagAgren** [comment]
Have you set the project up to copy the framework over in your test target?

**Comment by Dast1Woop** [comment]
Can you upload a picture about how to  "set the project up to copy the framework over in your test target" please?I can not understand this centence. @DagAgren

**Comment by wojciechczerski** [comment]
@Dast1990 Sorry for getting back to you so late but did you manage to solve your issue?

**Comment by wojciechczerski** [comment]
No feedback from the issue reporter. Closing the issue.
