### ISSUE TITLE
[Memory leaks] Memory keeps increasing for a running monkey

### ISSUE THREAD

**Issue by b1ueshad0w** [zalando/SwiftMonkey#23]
From Xcode's Debug Navigator, I notice that memory usage grows from 40MB to 80MB for an hour monkey running. I believe it will keep increasing as the monkey goes on. Thus the UITest will fail at the end because of OOM (maybe the tested app will OOM too).

**Comment by DagAgren** [comment]
Are you sure the app itself is not actually leaking memory?

**Comment by b1ueshad0w** [comment]
I am running the SwiftMonkeyExampleUITest on SwiftMonkeyExample. The point is Xcode's Debug Navigator can show the memory report of both the two processes (UITest and TestedApp). You can dive into any one of the two.
Also the screenshot says:
![screen shot 2017-02-28 at 5 33 33 pm](https://cloud.githubusercontent.com/assets/2503540/23399686/147ec530-fddc-11e6-9c0c-8b1a9958a9c0.png)

**Comment by DagAgren** [comment]
I did some quick testing, and I can reproduce a slow memory leak in the test process.

Trying to dig into it, though, it looks a little bit like the leak might be inside XCTest, so there is not much I can do about it, unless somebody can figure out something I am doing wrong with the private framework.

**Comment by singh88** [comment]
I tried profiling this at my end and profiled in my application. Here is the screenshot from the instruments. There are 6 memory leaks at the red button. It seems something wonky in the XCSynthesizedEventRecord. I have one suggestion, though it did not work in rectifying the memory leak. 

use of following code in all the closure calls. 

```
guard let `self` = self else {
                return
            }
```

<img width="1278" alt="screen shot 2017-08-16 at 3 30 35 pm" src="https://user-images.githubusercontent.com/5465858/29389098-2d595354-829d-11e7-8b48-24e253483d5d.png">
<img width="1283" alt="screen shot 2017-08-16 at 3 30 46 pm" src="https://user-images.githubusercontent.com/5465858/29389097-2d57cfac-829d-11e7-87e9-6c07daa6bc34.png">

**Comment by nexusCFX** [comment]
I'm running into this issue in my own project. The monkey can only run for 5-10 min before the test fails due to an OOM error.

**Comment by wojciechczerski** [comment]
I'll have a look at that @nexusCFX  and will get back to you as soon as I find something.

**Comment by b1ueshad0w** [comment]
I had rewritten this in an Objective-C version and solved this issue in the meantime. I will open-source it soon.
Ok, it's here: [OCMonkey](https://github.com/b1ueshad0w/OCMonkey)

**Comment by yingpaihuai** [comment]
public func monkeyAround(forDuration duration: TimeInterval = .infinity) {
        let monkeyTestingTime = Date().timeIntervalSince1970
        repeat {
//            fix it by add autoreleasepool
//            autoreleasepool {
                actRandomly()
                actRegularly()
//            }
        } while ((Date().timeIntervalSince1970 - monkeyTestingTime) < duration)
    }
