### ISSUE TITLE
Fix swipe actions to avoid pulling out the top and bottom panels

### ISSUE THREAD

**Issue by DagAgren** [zalando/SwiftMonkey#3]
The swipe actions can accidentally pull out panels from the top or bottom, which can let the monkey escape from the app, which can create more havoc than desired.

This could probably be fixed by avoiding certain coordinates when generating random swipes.

**Comment by drptbl** [comment]
#15 fixes this issue.

**Comment by DagAgren** [comment]
Thanks! I merged it, and then realised it can be done more efficiently so I did that.

I also updated the UIAutomation code to use it.

**Comment by drptbl** [comment]
@DagAgren I knew it can be done better way, thank you 👍 .
