### ISSUE TITLE
Linker command failed with exit code(use -v to see invocation)

### ISSUE THREAD

**Issue by Tangdawan** [zalando/SwiftMonkey#30]
When i run test case with real device, it shows build failed. Simulator can build and run monkey test 
 normally. The error message is : 
Apple Mach-O Linker (Id) Error
Linker command failed with exit code(use -v to see invocation)

Please help me， thanks

**Comment by joel-duqiong** [comment]
this problem also has happen to me 
xcode 8.3.2
ios 10.2

**Comment by wojciechczerski** [comment]
Most probably the reason is that **Bitcode** is enabled for the _SwiftMonkey_ target but _XCTests_ does not contain it. There is a pull request (https://github.com/zalando/SwiftMonkey/pull/26) that addresses this issue so as soon as it's merged, the linker issue should be solved.
