### ISSUE TITLE
Enable guided access to keep monkey from leaving the app

### ISSUE THREAD

**Issue by AVandelay** [zalando/SwiftMonkey#34]

**Comment by DagAgren** [comment]
I am not familiar with it, do you have some further information.

(Or even a PR, if I am pushing my luck?)

**Comment by AVandelay** [comment]
Guided Access prevents you from being able to exit the app. The issue with monkey testing is that it often pulls down the notification screen to reveal the search bar to query and leave the app's context. Here's a link to the documentation: 
https://developer.apple.com/documentation/uikit/uiguidedaccessrestrictiondelegate

I haven't worked with it so don't know if this can be set programmatically or whether XCUITest with XCode 9 will allow us to open the Settings app to enable guided access in the test's `SetUp()`

**Comment by nagashreeabhilash100** [comment]
Is there any update on this or workaround for this?

**Comment by wojciechczerski** [comment]
Closing the issue due to inactivity. Please reopen it if you think it should be addressed.
