### ISSUE TITLE
assertion failure

### ISSUE THREAD

**Issue by Le-Le-LeapFrog** [zalando/SwiftMonkey#36]
Assertion Failure: <unknown>:0: Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25204 getting snapshot for element <AXUIElement 0x1004357f0> {pid=6595}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element <AXUIElement 0x1004357f0> {pid=6595}}

**Comment by wojciechczerski** [comment]
Hey, thanks for your feedback! **Does this assertion appear in your app or in the sample app?** In case it's the sample, it should have already been solved by https://github.com/zalando/SwiftMonkey/pull/31.

**Comment by DagAgren** [comment]
This is basically a bug in Xcode. There is no general fix for it, just very random workarounds like the one mentioned by @wojciechczerski.

**Comment by wojciechczerski** [comment]
This issue has been fixed in iOS 11 (15A372).
