### ISSUE TITLE
in xcode8, run monkeytest in real device

### ISSUE THREAD

**Issue by monkeytest15** [zalando/SwiftMonkey#37]
I am the SwiftMonkey tool user, this tool is amazing~I like it very much

  But I want to run monkeytest in real device by xcode8, there is some solution for it?

**Comment by wojciechczerski** [comment]
Hi @monkeytest15! It's great to hear that you like the tool :) I am also happy to inform you that testing on a real device should be already possible! Just grab the latest changes from `master` and you should be all set.

If you are using [CocoaPods](https://cocoapods.org) to integrate the library just type in your _Podfile_:
> pod 'SwiftMonkey', :git => 'https://github.com/zalando/SwiftMonkey.git'

The latest `master` version of _SwiftMonkey_ is not yet released to _CocoaPods_ repository. We should do this soon and then you won't need to explicitly specify the repository URL.

**Comment by lasomethingsomething** [comment]
@wojciechczerski @monkeytest15 WDYT about adding a line to the README to make this clearer?

**Comment by wojciechczerski** [comment]
@LappleApple I think the goal should be to always have the latest changes released and pushed to the [CocoaPods](https://cocoapods.org) repository. Referencing a library by it's GitHub URL is not cool...

Let's try to summon @DagAgren here and ask him to make a release from the current `master`.

**Comment by DagAgren** [comment]
I should probably just add you to the cocoapod so you can do releases too. Do you have or can you register a cocoapod account, and give me the email and I'll add you as maintainer?

**Comment by wojciechczerski** [comment]
Perhaps I should have posted this comment a bit earlier... but there is a new release [1.0.2!](https://github.com/zalando/SwiftMonkey/releases/tag/1.0.2) 😄
