### ISSUE TITLE
What is the monkey click frequency?

### ISSUE THREAD

**Issue by cakushin** [zalando/SwiftMonkey#39]
What is the monkey click frequency?

**Comment by wojciechczerski** [comment]
SwiftMonkey does have a click frequency defined. All actions such as _tap_, _drag_ or _pinch_ are happening randomly. Each action has a _weight_ assigned making it possible to affect the probability at which the action is executed.

Take a look at [this actions configuration](https://github.com/zalando/SwiftMonkey/blob/master/SwiftMonkey/MonkeyXCTestPrivate.swift#L37). With the _weight_ value of 25 it makes _tap actions_ 5 times more likely to happen that any other action configured.
