### ISSUE TITLE
Proper test reporting.

### ISSUE THREAD

**Issue by singh88** [zalando/SwiftMonkey#40]
There should be some way to capture tap and other gesture events in either TestSummary.plist file or in some other reporting tool. Current implementation limits the use of SwiftMonkey to development machines if there is no reporting, then its hard to go back and see what happened during failure.

**Comment by wojciechczerski** [comment]
Hey @singh88! If I understood you correctly, you would like to record all the actions that resulted in an app crash / unexpected behavior and then be able to read them from a file (just like you pointed)?

The challenge I see here is how to make such information useful. A list of actions with associated positions might be difficult to use in finding a bug. However knowing exactly what button was hit before the app crashes would for sure guide you directly to the problem source (or a possible source).

I find your idea very interesting and I'll try to dig around to see what information can be gathered during the testing.

**Comment by singh88** [comment]
@wojciechczerski Yeah you are right!! It would be great to get the test result after SwiftMonkey execution just like the usual test reporting. I have tried playing around with Fastlane integration with this tool, but Fastlane parses TestSummary.plist file, not the console output. Also, I have tried using Fastlane snapshot mechanism to take a screenshot on every tap, but I got an error that snapshot works in the mainthread.

**Comment by singh88** [comment]
I was thinking to take a screenshot and log some meaningful statement, which would get logged in the TestSummary.plist file, and then use snapshot just before the Dispatch.semaphore call. 
This is how the snapshot of Fastlane works https://github.com/fastlane/fastlane/tree/master/snapshot#how-does-it-work. Which is pretty straightforward.
What would this give us? 
This will enable us to logs the test steps as well as take exact screenshots for the test steps, instead of a developer looking into all the screenshot that XCTest takes by default and figure out what was the root cause.

**Comment by wojciechczerski** [comment]
@singh88 I was thinking about the snapshot solution and I have an impression that having this combined with your initial idea (record executed actions) could provide some really useful debug information. For example if the tests crashes we get:
- a list of executed actions that we can provide to SwiftMonkey in order to execute them again and hopefully see the crash
- a screenshot showing the context in which the crash happened

What do you think? Would this be a useful solution?

**Comment by DagAgren** [comment]
The set of actions performed is already deterministic. With the same seed, the monkey will repeat the exact same actions. The problem is that since the response of the app is not deterministic, it will lead to different results anyway.

**Comment by singh88** [comment]
So, here is what I found useful, for my application. My app has a navigation bar on every screen so I divide my tests based on scenario's and navigate the monkey till that first screen and then create a frame by subtracting the maxY for the navigation bar. This helps in running the monkey test in a more restrictive way and limit its execution to only those scenarios.
I found snapshot integration more useful since it helps in visualizing what happened during the tests.

**Comment by deemicksee** [comment]
Would it be possible to add an Action that focuses on logging-via-screenshots?

Specifically:
- Take a screenshot every second, up to the limit specified in the Action (eg: 10 seconds max of screenshots)
- Each time the limit is hit, drop the oldest screenshot and overwrite it with the newest (eg: at 11 seconds, the first screenshot is dropped-and-replaced by the one taken at 11 seconds)
- Doing this would mean that, at app crash, we'd always have a visual journey of what the Monkey was up to

**Comment by wojciechczerski** [comment]
Closing the issue due to inactivity. Please reopen it if you think it should be addressed.
