### ISSUE TITLE
wrong type for index type

### ISSUE THREAD

**Issue by hpsoar** [zalando/SwiftMonkey#49]
https://github.com/zalando/SwiftMonkey/blob/1e14f2febdf4df1c957940e5fcdc378fe927f273/SwiftMonkey/MonkeyXCTest.swift#L37
https://github.com/zalando/SwiftMonkey/blob/1e14f2febdf4df1c957940e5fcdc378fe927f273/SwiftMonkey/MonkeyXCTest.swift#L38

`index`的类型为`UInt`，
但`func element(boundBy index: Int) -> XCUIElement`的参数类型为`Int`

**Comment by wojciechczerski** [comment]
Hi @hpsoar ! This issue is related to Swift 4 migration and it is being handled by #48. As soon as this pull request is merged the issue you have reported will be solved.

**Comment by graemerycyk** [comment]
Hi guys! Is there any news on this issue?

**Comment by wojciechczerski** [comment]
Hey, the #48 is still in progress. It was reviewed and now we're waiting for some small fixes to be done before we can merge.

**Comment by graemerycyk** [comment]
ah sorry, I mis-read, I thought the changes had also been fixed. I see them now 🤦‍♂️

**Comment by wojciechczerski** [comment]
@grycyk The #48 was merged! I'll try to make a release with Swift 4 support today.
