### ISSUE TITLE
How to find out the seed number?

### ISSUE THREAD

**Issue by upeugene** [zalando/SwiftMonkey#54]
I use random seed numbers to start test. 
How to figure out seed number when app is crashing? to reproduce test with this seed number.

**Comment by singh88** [comment]
This line is used to set seed value
https://github.com/zalando/SwiftMonkey/blob/befbf62a93d3ff24edba25d9de361edf3f2d88bc/SwiftMonkey/Monkey.swift#L99
You can get that value from here or you can pass this value from your test function and set this init with your seed value.
https://github.com/zalando/SwiftMonkey/blob/befbf62a93d3ff24edba25d9de361edf3f2d88bc/SwiftMonkey/Monkey.swift#L100
