### ISSUE TITLE
Cannot build SwiftMonkey from pods

### ISSUE THREAD

**Issue by PavelKatunin** [zalando/SwiftMonkey#60]
Cannot call value of non-function type 'XCUIElement'

    public func addXCTestTapAlertAction(interval: Int, application: XCUIApplication) {
        addAction(interval: interval) { [weak self] in
            // The test for alerts on screen and dismiss them if there are any.
            for i in 0 ..< application.alerts.count {
                let alert = application.alerts.element(boundBy: i)
                let buttons = alert.descendants(matching: .button)
                XCTAssertNotEqual(buttons.count, 0, "No buttons in alert")
                let index = UInt(self!.r.randomUInt32() % UInt32(buttons.count))
                let button = buttons.element(boundBy: index)
                button.tap()
            }
        }
    }

>>>>>>  let button = buttons.element(boundBy: index)

**Comment by wojciechczerski** [comment]
Hey @PavelKatunin! Could you please provide more details on the error? Is this something that stopped working after you made an update? Which Swift version are you using? Did you add SwiftMonkey to your UI tests target?

**Comment by lfarah** [comment]
Just got the same error. This is because the Readme example is pointing to 1.0 instead of the newest.
<img width="905" alt="screen shot 2018-08-13 at 13 50 52" src="https://user-images.githubusercontent.com/6511079/44045748-e72f3f3a-9eff-11e8-83a4-c2c40083314d.png">

**Comment by wojciechczerski** [comment]
The #62 that fixes the README has been merged. Closing the issue.
