### ISSUE TITLE
How to run test

### ISSUE THREAD

**Issue by jihun-im** [zalando/SwiftMonkey#66]
I am new to iOS.
I turned on iOS simulator and xcode.
When I tried 'Cmd+U' on the example, Xcode says that Build Succeeded.

What I expected is running monkey test. Could you tell me what am I missing?

![image](https://user-images.githubusercontent.com/1681072/46341085-48844700-c672-11e8-9182-113910b29ee8.png)

**Comment by jihun-im** [comment]
Build failed.
![image](https://user-images.githubusercontent.com/1681072/46342960-33f67d80-c677-11e8-86a8-9213704227bc.png)

**Comment by wojciechczerski** [comment]
Hey @jihunim, it looks like you are using the latest version of SwiftMonkey and Xcode 9 which is not compatible. Either update to Xcode 10 or specify in your Podfile `pod 'SwiftMonkey', '2.1.0'`. If you want to try out the sample app, after you checked out the source, switch to the `2.1.0` tag, for example:
```
git checkout tags/2.1.0
```
Please let me know if that helps.

**Comment by jihun-im** [comment]
Thank you very much!

**Comment by jihun-im** [comment]
I updated Xcode to version 10. It worked fine.
However, I have trouble using this tool as a framework.
As written in README.md, I added SwiftMonkeyPaws and SwiftMonkey.
However, build fails. Could you check this?

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/1681072/46785746-b36a0800-cd6d-11e8-94a8-b77bf92785f3.png">

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/1681072/46785756-bb29ac80-cd6d-11e8-91ac-91394af5dc79.png">

**Comment by wojciechczerski** [comment]
Hey there! I see you chose integrating SwiftMonkey without a dependency manager (like CocoaPods) which is slightly more difficult. I'll try however to guide you through the process.

1. Create an app.

![bildschirmfoto 2018-10-15 um 00 04 28](https://user-images.githubusercontent.com/1027098/46922826-2d6cec00-d00f-11e8-8d24-c00e05b27d30.png)

2. Find `SwiftMonkeyPaws.xcodeproj` in Finder.

![bildschirmfoto 2018-10-15 um 00 04 44](https://user-images.githubusercontent.com/1027098/46922850-51303200-d00f-11e8-8434-7eb96df8db3a.png)

3. Drag `SwiftMonkeyPaws.xcodeproj` onto your project in Xcode.

![bildschirmfoto 2018-10-15 um 00 04 53](https://user-images.githubusercontent.com/1027098/46922859-673df280-d00f-11e8-8527-3519c9eef7ec.png)

From your screenshots I see that you almost did this except for you didn't drag the `xcodeproj` file, but instead the folders containing project files.

4. Go to your target settings -> General -> Embedded Binaries. Press the + button and select `SwiftMonkeyPaws` from the list.

![bildschirmfoto 2018-10-15 um 00 05 58](https://user-images.githubusercontent.com/1027098/46922887-e8958500-d00f-11e8-8378-f52590b616d5.png)

Done! `SwiftMonkeyPaws` is now integrated into your app! This is an optional step but I assume you would like to see a visualization of random input generated by SwiftMonkey 😉 
Now let's move on to integrate `SwiftMonkey` into you'r UITests target.

5. Find `SwiftMonkey.xcodeproj` in Finder and drag it onto you'r project (just like we did with `SwiftMonkeyPaws`).

![bildschirmfoto 2018-10-15 um 00 07 09](https://user-images.githubusercontent.com/1027098/46922923-72dde900-d010-11e8-83d6-cb45ac924073.png)

7. Go to your UI tests target settings -> Build Phases -> Link With Libraries, press the + button and select `SwiftMonkey` from the list.

![bildschirmfoto 2018-10-15 um 00 07 28](https://user-images.githubusercontent.com/1027098/46922934-bafd0b80-d010-11e8-9fa3-d392d17727dd.png)

8. In the same view, press the "Add new build phase" button (1) and select "Copy Files". Press the + button (2) and `SwiftMonkey.framework` to the newly added "Copy Files" phase. Select "Frameworks" as Destination (3).

![bildschirmfoto 2018-10-15 um 00 08 32](https://user-images.githubusercontent.com/1027098/46922990-9f463500-d011-11e8-978d-7538d0b71bd8.png)

After all that is done you should have `SwiftMonkey` integrated successfully. Please let me know whether this helped 😏

**Comment by jihun-im** [comment]
Thank you for detailed explanation. I will try this and get back to you later.
If problem still occurs then I will reopen this.
Thank you very much :)

**Comment by jihun-im** [comment]
I followed your guide and it worked perfectly.
(I had to import SwiftMonkeyPaws, create a MonkeyPaws variable and initialize it.)
