### ISSUE TITLE
test failed when using xcode10 on a real device

### ISSUE THREAD

**Issue by danyating** [zalando/SwiftMonkey#67]
I have downloaded the newest code from github today. When I test  'SwiftMonkeyexampleTests', I run into this:
![image](https://user-images.githubusercontent.com/12235603/46602835-fa7aa380-cab6-11e8-92f2-002226ef59ed.png)
However, I can run it on a simulator successfully. But when I run it on a real device, it fails.
How can I solve this problem? thanks.

**Comment by wojciechczerski** [comment]
Hey @danyating and sorry for a late reply. I was reproduced the issue you're facing but I couldn't find a solution how to fix it. I'll mark the issue as "Help wanted". Sorry for not having optimistic news 😞 

I will give it a try this weekend with the newest Xcode and will keep you informed.

**Comment by danyating** [comment]
@wojciechczerski  Thanks for the reply. I have already solved this problem, by simply adding "Copy Files" build phases.
![image](https://user-images.githubusercontent.com/12235603/47982459-612eb500-e095-11e8-9017-634e10625ea4.png)
So I'm going to close this issue. Thanks.
