### ISSUE TITLE
Test launch failing 

### ISSUE THREAD

**Issue by vbavareddy** [zalando/SwiftMonkey#69]
Hi,
I am facing below error while running tests. 
SwiftMonkeyExampleUITests-Runner.app (74021) encountered an error (Timed out waiting for AX loaded notification)

Tests run on setup:
Xcode Version 10.0 (10A255)
iOS Deployment target: iOS 11.0
Target simulator: iPhone 8 plus

Please help.

**Comment by wojciechczerski** [comment]
Hey there, and sorry for a very late come back. Is this the example app you are testing or your own app in which you integrated SwiftMonkey?

**Comment by wojciechczerski** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen it if you think it should be addressed.
