### ISSUE TITLE
Does swiftmonkeyPaws support Xcode10+,ios 12?

### ISSUE THREAD

**Issue by Fred0218** [zalando/SwiftMonkey#72]
Does swiftmonkeyPaws support Xcode10+,ios 12?
I have add swiftmonkey and swiftmonkeyPaws to project,when monkey running,now paws display,why?

**Comment by wojciechczerski** [comment]
Hey @Fred0218 ! Are you using the example app or your own? Did you configure the `SwiftMonkeyPaws` properly? For example as it is done in the [AppDelegate.swift](https://github.com/zalando/SwiftMonkey/blob/master/SwiftMonkeyExample/App/AppDelegate.swift#L19) of the example app.

**Comment by Fred0218** [comment]
thanks for reply!
i use my own app,swiftmonkeypaw not work,but your example app monkeypaws work.
also i have configed in the  AppDelegate.swift like example app.

app code:
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var paws: MonkeyPaws?
    
    var isOnline: Bool = true
    var window: UIWindow?

    var isLandscape = false

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        
        if CommandLine.arguments.contains("--MonkeyPaws") {
            paws = MonkeyPaws(view: window!)
        }
        // Override point for customization after application launch.
        
        initializeLogging()
//        LocaleManager.initialize()
        Localizer.DoTheSwizzling()
        
        InAppPurchase.defaultInstance.fetchAvailableProducts()
        
        HBOStyle.configureAppearance()

        UserPreferences.registerDefaultPreferences()
        
        UserPreferences.apiLocal = "SGP" // temp
        UserPreferences.channelPartnerID = "HBO_Asia"
        
        createMainWindow()
        
        ToastManager.shared.style.backgroundColor = .lightGray
        
        
        do {
            try OMGDownloadManager.setup()
        }
        catch {
            AppLog.error("Error creating download manager: \(error)")
            fatalError()
        }
        // Set playback category mode to allow playing audio on the video files even
        // when the ringer mute switch is on.
        do {
            try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default)
        } catch let setCategoryError {
            print("Error setting audio category: \(setCategoryError.localizedDescription)")
        }

        Chromecast.shared.initialize(nil)
        
//        let bootstrapServer = BootstrapServer()
        guard ConnectivityManager(baseURL: URL(string: "https://www.apple.com")!) != nil else {
            fatalError("Cannot create connectivity manager")
        }
        
        createAPI()
        
        return true
    }

**Comment by Fred0218** [comment]
this ticket can be closed,though my paws not work,but your example app works.
open project you used xxx.codeproj,but i used xxx.xcworkspace,if i use xxx.xcodeproj to open project,some dependencies will compile failed,this will caused monkeypaws failed???

**Comment by wojciechczerski** [comment]
@Fred0218 When using CocoaPods you need to always open the workspace file. This could be the reason for the errors you were encountering.

Should I close this issue? Or you could simply do it if your problem is solved.
