### ISSUE TITLE
OC project use SwiftMonkey,but MonkeyPaws doesn't have a init func

### ISSUE THREAD

**Issue by zidonJ** [zalando/SwiftMonkey#78]
OC project use SwiftMonkey,but MonkeyPaws doesn't have a init func
<img width="678" alt="image" src="https://user-images.githubusercontent.com/8241422/55928113-1a4b7980-5c4a-11e9-9a5d-0f78debeccc1.png">

**Comment by yangjunpeng1993** [comment]
I have the same problem? Do you resolve it ?

**Comment by yangjunpeng1993** [comment]
> OC project use SwiftMonkey,but MonkeyPaws doesn't have a init func
> <img alt="image" width="678" src="https://user-images.githubusercontent.com/8241422/55928113-1a4b7980-5c4a-11e9-9a5d-0f78debeccc1.png">

I have the same problem? Do you resolve it ?

**Comment by Bintong** [comment]
I have the same problem? Do you resolve it ?

**Comment by riceForChina** [comment]
You can use the swift function to wrap a layer

 @objc static func createSwiftMonkey(view: UIView) -> MonkeyPaws{
        return MonkeyPaws(view: view)
    }

**Comment by wojciechczerski** [comment]
Closing the issue due to inactivity. Please reopen it if you think it should be addressed.
