### ISSUE TITLE
Configure the length of test run

### ISSUE THREAD

**Issue by westdorp** [zalando/SwiftMonkey#88]
Is it possible to configure how long the monkey test runs by time or event count?

**Comment by wojciechczerski** [comment]
Please have a look at [`Monkey.monkeyAround(forDuration duration: TimeInterval = .infinity)`](https://github.com/zalando/SwiftMonkey/blob/master/SwiftMonkey/Monkey.swift#L160). You might also be interested in [`Monkey.monkeyAround(iterations: Int)`](https://github.com/zalando/SwiftMonkey/blob/master/SwiftMonkey/Monkey.swift#L149).
