### ISSUE TITLE
Add more customisability for MonkeyPaws visualisation

### ISSUE THREAD

**Issue by DagAgren** [zalando/SwiftMonkey#9]
Currently there is no way to customise how the events are visualised. There should be some way, such as subclassing or adding closures to provide custom drawing.

**Comment by dirtydanee** [comment]
Hey! We just ran into this issue of customising the paws various attributes. The drawing for us is fine, but we would like to adjust the number, the brightness and the colour of the paws. 

Would you be open for a PR where i would create a configuration with some properties (you could tell me what on top of the ones i mentioned) to be passed in to configure visual layout of the paws?

**Comment by wojciechczerski** [comment]
Hello @dirtydanee and sorry for the late reply. Regarding your question - of course we would be interested! You can start directly with a PR or if you prefer we can discuss first what and how to implement here. One question though - how should customizing **number of paws** work?

**Comment by dirtydanee** [comment]
Hey @wojciechczerski, thanks for the reply! 

Number of paws -> Sorry for the confusion, I meant **the number of visible paws**. 
We wanted to make visible only the last 5 paws, not all of the ones, that have occurred during a test. I hope this clears my intention. 

I will open a PR in the next week, and lets take it from there.

**Comment by wojciechczerski** [comment]
The #57 has been merged. Closing the issue.
